artifact: artificial
artifact_type: microscope
attacked_classes:
- MEL
p_artifact: False
batch_size: 64
data_paths:
- /ritter/roshan/workspace/ICON/experiments/melanoma/dataset/microscope-40/
dataset_name: isic
device: cuda:4
eval_every_n_epochs: 5
img_size: 224
loss: cross_entropy
lr: 0.001
milestones: 100,150
model_name: vgg16
model_savedir: /ritter/roshan/workspace/medical-ai-safety/model_checkpoints/
num_epochs: 201
optimizer: sgd
pretrained: true
store_best_model: true
store_every_n_epochs: 200
# wandb_api_key: YOUR_WANDB_KEY
# wandb_project_name: isic-real-training
